name: build

on:
  push:
  pull_request:
  schedule:
  - cron: "42 20 * * 6"  # Run at a random time weekly

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: [2.7, 3.8]
        imp-branch: [master, develop]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Setup conda
      run: |
        support/tutorial_tools/setup_travis.sh ~/conda ${{ matrix.imp-branch }} ${{ matrix.python-version }}
    - name: Test
      run: |
        source ~/conda/bin/activate python${{ matrix.python-version }}
        conda install --yes -q scikit-learn
        nosetests --exe support/test
